In [1]:
# Numpy
import numpy as np

In [2]:
# Searching Arrays:

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

# The example above will return a tuple: (array([3, 5, 6],)
# Which means that the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [16]:
# Search Sorted:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 10) 

print(x)

# returns the index where the specified value would be inserted to maintain the search order.

4


In [19]:
# Search From the Right Side:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side="right") 

print(x)

# returns the index where the specified value would be inserted to maintain the search order. starting from the right.

2


In [20]:
# Multiple Values:

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

# To search for more than one value, use an array with the specified values.

[1 2 3]


In [21]:
# Sorting Arrays:

arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

# Sorting means putting elements in an ordered sequence.
# This method returns a copy of the array, leaving the original array unchanged.
# You can also sort arrays of strings, or any other data type.

[0 1 2 3]


In [22]:
# Sorting a 2-D Array:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

# If you use the sort() method on a 2-D array, both arrays will be sorted

[[2 3 4]
 [0 1 5]]


In [23]:
# Filtering Arrays:

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

# In NumPy, you filter an array using a boolean index list.
# If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

[41 43]


In [25]:
# Creating Filter Directly From Array:

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

# We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

[False False  True  True]
[43 44]
