In [1]:
# Numpy
import numpy as np

# Shape of an Array

# Get the Shape of an Array:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 
# The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.


(2, 4)


In [3]:
# Array Reshaping

# Reshape From 1-D to 2-D:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3) # The outermost dimension will have 4 arrays, each with 3 elements

print(newarr)

print("\n")

# Reshape From 1-D to 3-D:

newarr = arr.reshape(2, 3, 2) #The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 element

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
""" 
Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
"""

In [ ]:
# Unknown Dimension: 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1) # Pass -1 as the value, and NumPy will calculate this number for you.

print(newarr)

In [ ]:
# Flattening Arrays: 

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1) # Convert the array into 1-D

print(newarr)