In [6]:
#Numpy:
import numpy as np

# Iterating Arrays:

# Iterating the elements of a 1-D array:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

print("\n")

# Iterating the elements of a 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

print("\n")

# Iterating the elements of a 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

print("\n")


# To return the actual values, the scalars, we have to iterate the arrays in each dimension.

# Iterating on Each Scalar Element:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr): 
  print(x)

1
2
3


[1 2 3]
[4 5 6]


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


1
2
3
4
5
6
7
8


In [10]:
# Iterating Array With Different Data Types

# We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1.0'
b'2.9'
b'3.5'


In [11]:
# Iteration with different Step Size:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]): # Iterate through every scalar element of the 2D array skipping 1 element
  print(x)

1
3
5
7


In [14]:
# Enumerated Iteration:

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

print("\n")

# Enumerate on following 2D array's elements:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr): 
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [33]:
# Joining Arrays:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

print("\n")

# Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)



[1 2 3 4 5 6]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [32]:
# Joining Arrays Using Stack Functions:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
# Stacking Along Rows:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [30]:
# Stacking Along Columns:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [29]:
# Stacking Along Height (depth):

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
