In [2]:
# Numpy
import numpy as np

# Array Slicing:

# Slicing 1-D Arrays:
arr_1 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr_1[1:5])

# Slicing 2-D Arrays:
arr_2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("From the second array, slice elements from index 1 to index 4 (not included):", arr_2[1, 1:4])
print("From both elements, return index 0:", arr_2[0:2, 0])
print("From both elements, return elementos from index 1 to to index 4 (not included):", arr_2[0:2, 1:4])



[2 3 4 5]
From the second array, slice elements from index 1 to index 4 (not included): [7 8 9]
From both elements, return index 0: [1 6]
From both elements, return elementos from index 1 to to index 4 (not included): [[2 3 4]
 [7 8 9]]


In [14]:
# Data Types:

# i - integer
# b - boolean
# u - unsigned integer (non-negative)
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

# Checking the Data Type of an Array:

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


In [18]:
# Creating Arrays With a Defined Data Type:

arr = np.array([1, 2, 3, 4], dtype="S") # Array with data type string

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [17]:
# Converting Data Type on Existing Arrays:

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype("i") # Converts from float to integer

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [4]:
# Array Copy and View:

arr = np.array([1, 2, 3, 4, 5])

# Copy:
x = arr.copy()

# View:
y = arr.view()

print(arr)
print(x)
print(y)

print("\n")

# The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

x[0] = (34)
print(arr)
print(x)

print("\n")

# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

y[0] = (34)
print(arr)
print(x)

print("\n")

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


[1 2 3 4 5]
[34  2  3  4  5]


[34  2  3  4  5]
[34  2  3  4  5]


None
