In [1]:
# NumPy ufuncs ("Universal Functions")
import numpy as np

# Example:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]

z = np.add(x, y) # Add the Elements of Two Lists

print(z)

[ 5  7  9 11]


In [4]:
# How To Create Your Own ufunc:

# frompyfunc() method takes the following arguments:

# function - the name of the function.
# inputs - the number of input arguments (arrays).
# outputs - the number of output arrays.

# Example:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [5]:
# Check if a Function is a ufunc: 

# Check the type of a function to check if it is a ufunc or not.
# A ufunc should return <class 'numpy.ufunc'>.

# Example:
print(type(np.add))

<class 'numpy.ufunc'>


In [6]:
# Simple Arithmetic:

# Addition:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [7]:
# Subtraction:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [8]:
# Multiplication:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [9]:
# Division:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)


[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [12]:
# Power:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [13]:
# Remainder:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [14]:
# Quotient and Mod:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [15]:
# Absolute Values:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [ ]:
# Rounding Decimals:

# There are primarily five ways of rounding off decimals in NumPy:

# truncation
# fix
# rounding
# floor
# ceil

In [16]:
# Truncation: Remove the decimals, and return the float number closest to zero.
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [17]:
# Rounding: round off to 1 decimal point.
arr = np.around(3.1666, 2) # 2 decimal places

print(arr)

3.17


In [18]:
# Floor: rounds off decimal to nearest lower integer.
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [19]:
# Ceil: rounds off decimal to nearest upper integer.
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [20]:
# NumPy Logs

# Log at Base 2:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [21]:
# Log at Base 10: 
arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [23]:
# Natural Log, or Log at Base e:
arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [24]:
# Log at Any Base:
from math import log

nplog = np.frompyfunc(log, 2, 1) 

print(nplog(100, 15))

1.7005483074552052


In [25]:
# NumPy Summations:

# Example:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [30]:
# Summation Over an Axis: 
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)


[6 6]


In [31]:
# Cummulative Sum:
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


In [32]:
# NumPy Products:

# Example: 
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

# Returns: 24 because 1*2*3*4 = 24


24


In [33]:
# Product of the elements of two arrays:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

# Returns: 40320 because 1*2*3*4*5*6*7*8 = 40320

40320


In [34]:
# Product Over an Axis:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

# Returns: [24 1680]


[  24 1680]


In [35]:
# Cummulative Product:

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

# Returns: [5 30 210 1680]

[   5   30  210 1680]


In [36]:
# NumPy Differences:

# Example: 
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

# Returns: [5 10 -20] because 15-10=5, 25-15=10, and 5-25=-20


[  5  10 -20]


In [ ]:
# Discrete difference of the following array twice:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

# Returns: [5 -30] because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30

In [37]:
# LCM Lowest Common Multiple:

# Finding LCM:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

# Returns: 12 because that is the lowest common multiple of both numbers (4*3=12 and 6*2=12).

12


In [40]:
# Finding LCM in Arrays: 

# To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.

# The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

# Example:
arr = np.array([3, 6, 9, 12, 18])

x = np.lcm.reduce(arr)

print(x)

36


In [42]:
# GCD Greatest Common Denominator

# Finding GCD:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

# Returns: 3 because that is the highest number both numbers can be divided


3


In [43]:
# Finding GCD in Arrays:

# To find the Highest Common Factor of all values in an array, you can use the reduce() method.

# Example:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

# Returns: 4 because that is the highest number all values can be divided by.

4


In [44]:
# Trigonometric Functions: 

# NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

# Example: 
x = np.sin(np.pi/2)

print(x)

1.0


In [46]:
# Find sine values for all of the values in arr:

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [47]:
# Convert Degrees Into Radians: 
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

# radians values are pi/180 * degree_values.

[1.57079633 3.14159265 4.71238898 6.28318531]


In [48]:
# Convert Radians Into Degrees: 
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [49]:
# Finding Angles:

# Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

# NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

# Example: 
x = np.arcsin(1.0)

print(x)


1.5707963267948966


In [50]:
# Angles of Each Value in Arrays: 
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [51]:
# Hypotenues: 

# Finding hypotenues using pythagoras theorem in NumPy.

# NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

# Example: 
base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [52]:
# NumPy Hyperbolic Functions: 

# NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values. 

# Example: 
x = np.sinh(np.pi/2)

print(x)

2.3012989023072947


In [53]:
# Find cosh values for all of the values in arr:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [54]:
# Finding Angles:

# Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

# Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

# Example: 
x = np.arcsinh(1.0)

print(x)

0.881373587019543


In [55]:
# Angles of Each Value in Arrays:
arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


In [56]:
# NumPy Set Operations: 

# A set in mathematics is a collection of unique elements.

# Create Sets in NumPy: 
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)


[1 2 3 4 5 6 7]


In [57]:
# Finding Union: 

# To find the unique values of two arrays, use the union1d() method.

# Example: 
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [58]:
# Finding Intersection

# To find only the values that are present in both arrays, use the intersect1d() method.

# Example: 
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [60]:
# Finding Difference:

# To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

# Example:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [61]:
# Finding Symmetric Difference:

# To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

# Example:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
