In [2]:
# Numpy
from numpy import random

In [4]:
# Generate Random int Number:

x = random.randint(100)

print(x)

5


In [ ]:
# Generate Random Float:

x = random.rand()

print(x)

In [8]:
# Generate Random int Array

# Generate a 1-D array containing 5 random integers from 0 to 100:

x=random.randint(100, size=(5))

print(x)

[ 8 78 75 95  7]


In [9]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x = random.randint(100, size=(3, 5))

print(x)


[[ 9 70 41 29 44]
 [ 9 65 98 29 10]
 [87 16 39 30 59]]


In [10]:
# Generate Random float Array

# Generate a 1-D array containing 5 random floats:

x = random.rand(5)

print(x)

[0.22367022 0.55265324 0.99114961 0.50516645 0.91503549]


In [11]:
# Generate a 2-D array with 3 rows, each row containing 5 random float numbers:

x = random.rand(3, 5)

print(x)

[[0.38185445 0.08416683 0.09317303 0.93788831 0.86036815]
 [0.34919953 0.74941928 0.07353471 0.50104461 0.15451797]
 [0.66463211 0.01266764 0.45745596 0.51576085 0.49668463]]


In [20]:
# Generate Random Number From Array

# Return one of the values in an array:

x = random.choice([3, 5, 7, 9])

print(x) 

7


In [22]:
# Generating 2-D Arrays

# Add a size parameter to specify the shape of the array: 

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 3 3 7 3]
 [5 3 3 5 5]
 [9 7 5 9 3]]


In [26]:
# Random Distribution

# Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
# The probability for the value to be 3 is set to be 0.0 = 0%
# The probability for the value to be 5 is set to be 0.8 = 80%
# The probability for the value to be 7 is set to be 0.1 = 10%
# The probability for the value to be 9 is set to be 0.1 = 10%

x = random.choice([3, 5, 7, 9], p=[0, 0.8, 0.1, 0.1], size=(100))

print(x)


[5 9 5 5 5 7 9 5 5 5 5 5 7 5 5 5 5 5 9 5 5 9 7 5 5 5 5 5 9 7 5 5 5 5 5 5 5
 7 5 5 5 5 5 5 5 5 5 5 5 7 5 9 5 9 5 9 7 5 9 5 5 9 5 5 5 5 5 9 5 9 5 9 9 5
 5 5 5 5 5 5 5 5 5 7 9 5 7 5 9 5 9 5 5 5 5 5 7 5 5 5]


In [28]:
# Generate a 2-D array with 3 rows, each containing 5 values.
# The probability for the value to be 3 is set to be 0.0 = 0%
# The probability for the value to be 5 is set to be 0.8 = 80%
# The probability for the value to be 7 is set to be 0.1 = 10%
# The probability for the value to be 9 is set to be 0.1 = 10%

x = random.choice([3, 5, 7, 9], p=[0, 0.8, 0.1, 0.1], size=(3, 5))

print(x)

[[9 5 5 5 9]
 [5 7 5 5 9]
 [5 5 5 5 5]]


In [30]:
# Random Permutations of Elements

# Shuffling Arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

# The shuffle() method makes changes to the original array.

[5 2 4 1 3]


In [32]:
# Generating Permutation of Arrays:

arr = np.array([1, 2, 3, 4, 5])

arr_2 = (random.permutation(arr))

print(arr_2)

# The permutation() method returns a re-arranged array (and leaves the original array un-changed).

[3 1 5 2 4]
